# Generated by Django 2.0.2 on 2018-02-08 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0003_auto_20180208_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='company_name',
        ),
    ]
