# Generated by Django 2.0.2 on 2018-02-12 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0004_auto_20180208_2238'),
    ]

    operations = [
        migrations.RenameModel('Tag', 'Skill'),
        migrations.RenameField('Skill', 'tag_text', 'skill_text'),
        migrations.RenameField('JobPostingTag', 'tag', 'skill'),
        migrations.RenameField('ApplicantTag', 'tag', 'skill'),
    ]
