# Generated by Django 2.0.2 on 2018-02-13 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staffing', '0006_auto_20180212_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='applicants',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='job_postings',
        ),
        migrations.RemoveField(
            model_name='applicantskill',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='jobpostingskill',
            name='skill',
        ),
        migrations.AddField(
            model_name='applicant',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AddField(
            model_name='applicantskill',
            name='skill_text',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AddField(
            model_name='jobpostingskill',
            name='skill_text',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
