# Generated by Django 2.0.2 on 2018-02-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0009_auto_20180213_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(max_length=70),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='email',
            field=models.EmailField(max_length=70),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='email',
            field=models.EmailField(max_length=70, unique=True),
        ),
    ]
