# Generated by Django 2.0.2 on 2018-02-27 23:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0012_jobposting_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
    ]
