# Generated by Django 2.0.2 on 2018-03-07 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0014_applicant_resume_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
    ]
