# Generated by Django 2.0.2 on 2018-03-07 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0015_auto_20180307_1910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={},
        ),
        migrations.AlterModelOptions(
            name='recruiter',
            options={},
        ),
    ]
