# Generated by Django 2.0.2 on 2018-03-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0016_auto_20180307_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resume_files/%Y/%m/%d/<django.db.models.fields.CharField>/'),
        ),
    ]
