# Generated by Django 2.0.2 on 2018-03-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0017_auto_20180307_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resume_files/%Y/%m/%d/'),
        ),
    ]
